# Generated by Django 5.0.2 on 2024-04-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalsitesexpenseamount',
            name='LabourTotal',
        ),
        migrations.RemoveField(
            model_name='totalsitesexpenseamount',
            name='expenseTotal',
        ),
        migrations.RemoveField(
            model_name='totalsitesexpenseamount',
            name='toolTotal',
        ),
        migrations.CreateModel(
            name='TotalSitesToolAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tool_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
