# Generated by Django 5.0.2 on 2024-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=100),
            preserve_default=False,
        ),
    ]
