# Generated by Django 5.0.2 on 2024-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_attendance_present_or_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
