# Generated by Django 5.0.2 on 2024-03-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_attendance_total_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
